import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThirdwebProvider } from "thirdweb/react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`bg-yellow`}>
				<ThirdwebProvider>
					<Navbar />

					<div className="max-w-screen-2xl mx-auto py-6">
						{children}
					</div>
				</ThirdwebProvider>
			</body>
		</html>
	);
}
